# 5.4. 自定义层

# 5.4.1. 不带参数的层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-09, grad_fn=<MeanBackward0>)

# 5.4.2. 带参数的层

In [10]:
# 注意：需要用张量, nn.Parameter.data
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units), requires_grad=True)
        self.bias = nn.Parameter(torch.randn(units), requires_grad=True)
        # self.bias = nn.Parameter(torch.zeros(units), requires_grad=True)
    
    def forward(self, X):
        return F.relu(torch.mm(X, self.weight.data) + self.bias.data)

In [7]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.3326,  0.3923, -0.0513],
        [ 0.0119,  0.3754,  0.0098],
        [-1.1699, -0.9592,  0.3168],
        [ 1.0706,  0.3451, -0.4142],
        [-1.8220,  1.2166,  1.5662]], requires_grad=True)

In [8]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0587, 0.7666],
        [0.0624, 0.2752, 0.0680]])

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.4235],
        [1.8009]])

# 5.4.3. 小结

我们可以通过基本层类设计自定义层。这允许我们定义灵活的新层，其行为与深度学习框架中的任何现有层不同。

在自定义层定义完成后，我们就可以在任意环境和网络架构中调用该自定义层。

层可以有局部参数，这些参数可以通过内置函数创建。

# 5.4.4. 练习